import os

# Telegram bot token
TOKEN = os.getenv(
    "BOT_TOKEN", "your-bot-token"
)  # Bot Token generated by Telegram BotFather


URL = os.getenv(
    "URL",
    "https://esii-orion.com/orion-reservation/slots?account=EVMSPI&config=SEJOURUSARNVT&usemode=app&code=REN1",
)


# Default frequency for checking appointments in seconds
DEFAULT_FREQUENCY = int(
    os.getenv("DEFAULT_FREQUENCY", 1800)
)  # 30min (WARNING !!! A too high frequency can be considered as an DOS attack, be careful)


CHROMIUM_PATH = os.getenv(
    "PUPPETEER_EXECUTABLE_PATH",
    "/usr/bin/chromium",
)  # Path to Chromium executable
